name: xs

# training
total_steps: 100000
warmup_steps: 500
batch_size: 1
learning_rate: 0.0001
weight_decay: 0.1
betas: [0.9, 0.95]

# architecture
hidden_size: 8
n_heads: 2
n_layers: 4
n_pixels: 32
n_clusters: 6

# dropout probabilities
mlp_pdrop: 0.5
attn_pdrop: 0.5
resid_pdrop: 0.5
embed_pdrop: 0.5

